apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-asmn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-asmn
    app.kubernetes.io/part-of: my-app-2
  name: devfile-sample-asmn
spec:
  rules:
  - host: devfile-sample-asmn-karthik-jk-tenant.192.168.49.2.nip.io
    http:
      paths:
      - backend:
          service:
            name: devfile-sample-asmn
            port:
              number: 3001
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
